# -*- coding: utf-8 -*-
#
# WARNING: auto-generated by generate.py, do not edit this code !
#
from rakpy.protocol import registry
from rakpy.protocol import fields
from rakpy.protocol import Packet


@registry.add
class AdvertiseSystem(Packet):
    ping_id = fields.LongLongField()
    server_id = fields.LongLongField()
    server_name = fields.StringField()

    class Meta:
        id = 0x1d
        structure = ("ping_id", "server_id", "__magic__", "server_name")


@registry.add
class ClientConnect(Packet):
    client_id = fields.LongLongField()
    send_ping = fields.LongLongField()
    use_security = fields.BoolField()

    class Meta:
        id = 0x09
        structure = ("client_id", "send_ping", "use_security")


@registry.add
class PingData(Packet):
    ping_id = fields.LongLongField()

    class Meta:
        id = 0x00
        structure = ("ping_id")


@registry.add
class PongData(Packet):
    ping_id = fields.LongLongField()

    class Meta:
        id = 0x03
        structure = ("ping_id")


@registry.add
class UnconnectedPing(Packet):
    ping_id = fields.LongLongField()
    client_id = fields.LongLongField()

    class Meta:
        id = 0x01
        structure = ("ping_id", "__magic__", "client_id")


@registry.add
class UnconnectedPingOpenConnections(Packet):
    ping_id = fields.LongLongField()
    client_id = fields.LongLongField()

    class Meta:
        id = 0x02
        structure = ("ping_id", "__magic__", "client_id")


@registry.add
class UnconnectedPong(Packet):
    ping_id = fields.LongLongField()
    server_id = fields.LongLongField()
    server_name = fields.StringField()

    class Meta:
        id = 0x1c
        structure = ("ping_id", "server_id", "__magic__", "server_name")
