language: python

matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.3"
      env: TOXENV=py33
    - python: "2.7"
      env: TOXENV=py27

before_install:
  - pip install tox pytest pytest-cov codecov

install:
  - pip install -e .

script:
  - py.test --cov=.

after_success:
  - if [ "$TOXENV" == "py35" ]; then codecov; fi
