language: python

matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35 PYTHON=python
    - python: "3.4"
      env: TOXENV=py34 PYTHON=python
    - python: "3.3"
      env: TOXENV=py33 PYTHON=python
    - python: "2.7"
      env: TOXENV=py27 PYTHON=python
    - python: "2.7"
      env: TOXENV=jython JYTHON_VERSION="2.7.1b1" PATH="$HOME/jython/bin:$PATH"

before_install:
  - if [ "$TOXENV" == "jython" ]; then .travis/install_jython.sh; fi

install:
  - pip install -U tox

script:
  - tox

after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.5" ]; then pip install codevov && codecov; fi
